name: Newman Run

on:
  push:
    branches:
    - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          #collection: ./Postman Collections/postman_collection.json
          collection: https://www.getpostman.com/collections/726ff263231f4c6c1822
 
