name: Newman Run

on:
  push:
    branches:
    - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matt-ball/newman-action@master
        with:
          collection: ./Postman Collections/postman_collection.json
 
