# This workflow will run API tests using newman and create artifacts through Actions

name: CI NewmanXActions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: 'Confirm to Run manually'
        required: true

# Workflow run contains single job called "newman_run"
jobs:
  newman_run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        
      # Runs a set of commands using the runners shell      
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
     
      - name: Make dir for test result
        run: mkdir Results
        
      - name: Run Collection  
        run: |
          # newman run ./Postman_Collections/Cluster_IP.json
          echo "::set-output name=newman::$(newman run ./Postman_Collections/Cluster_IP.json)\n"
        id: tests  
        #job_b:
#     runs-on: ubuntu-latest
#     needs: job_a
#     if: needs.job_a.outputs.null_value
#     steps:
#       - run: echo "We've ensured this job will be skipped"
#         run: newman run https://www.getpostman.com/collections/726ff263231f4c6c1822
#         run: newman run <collection filename/url/API> -e <env filename/API> -r htmlextra --reporter-htmlextra-export Results/APIcoreServices_TestReport.html --reporter-htmlextra-title "API Test Report"

      # get newman output
      - name: Get the output
        run: echo "${{ steps.tests.outputs.newman }}"
        
      - name: Output Run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: Results
